#!/usr/bin/env bash
set -e

HELP_TEXT=$(cat << _EOF_
jhome 0.0.1
Usage: jhome <command> [<args>]

Some useful jhome commands are:
install     Install a JDK
list        List installed JDKs

See 'jhome help <command>' for information on a specific command.
For full documentation, see: https://github.com/reyesyang/jhome#readme
_EOF_
)

print_help() {
   echo "$HELP_TEXT"
}

command=$1

case $command in
    list)
        exec commands/jhome_list;;
    install)
        exec commands/jhome_install;;
    *)
        print_help;;
esac
