#!/usr/bin/env bash
set -e

HELP_TEXT=$(cat << _EOF_
jhome 0.0.1
Usage: jhome <command> [<args>]

Some useful rbenv commands are:
commands    List all available rbenv commands
local       Set or show the local application-specific Ruby version
global      Set or show the global Ruby version
shell       Set or show the shell-specific Ruby version
install     Install a Ruby version using ruby-build
uninstall   Uninstall a specific Ruby version
rehash      Rehash rbenv shims (run this after installing executables)
version     Show the current Ruby version and its origin
versions    List installed Ruby versions
which       Display the full path to an executable
whence      List all Ruby versions that contain the given executable

See 'jhome help <command>' for information on a specific command.
For full documentation, see: https://github.com/reyesyang/jhome#readme
_EOF_
)

print_help() {
   echo "$HELP_TEXT"
}

command=$1

case $command in
    list)
        exec commands/jhome_list;;
    install)
        exec commands/jhome_install;;
    *)
        print_help;;
esac
